import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
// import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from './context/AuthContext';

// Load custom fonts


// Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <AuthProvider>
          {children}
          <Analytics />
        </AuthProvider>
      </body>
    </html>
  );
}
